import React from 'react'
import Head from 'next/head'
import { Box, ButtonGroup, Button, Typography} from '@mui/material'

const CategoryPage = () => {
  return (
    <div> 
        <Head>
          <title>Categories</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Box sx={{minHeight: "100vh", display:"flex", justifyContent:"center", alignItems: "center"}}>
          <Box 
          sx={{
            width: "100%",
            maxWidth: "900px",
            minHeight: "400px", 
            padding:"20px 10px",
            backgroundColor: "rgba(0,0,0, .5)",
            borderRadius:"8px", 
            boxShadow: "0px 2px 8px 6px rgba(251, 251, 251, 0.2)", 
            display:"flex", justifyContent:"center", alignItems: "center",flexDirection:"column"
          }}>
            <Typography variant='h3' component="h3" sx={{fontStyle: "italic",mb:"20px", background: "linear-gradient(to left, #00FF00 0%, #FF0000 100%"}}>All categories</Typography>
            <ButtonGroup variant="outlined" aria-label="outlined button group">
              <Button sx={{padding: "10px 40px"}}>One</Button>
              <Button sx={{padding: "10px 40px"}}>Two</Button>
              <Button sx={{padding: "10px 40px"}}>Three</Button>
            </ButtonGroup>
          </Box>
        </Box>
    </div>
  )
}

export default CategoryPage