import Head from 'next/head'
import React from 'react'

const BlogPage = () => {
  return (
    <>
        <Head>
            <title>Blogs</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    </>
  )
}

export default BlogPage