import { Box, Button } from '@mui/material'
import Head from 'next/head'
import { Hero } from 'src/components'

export default function Home() {
  return (
    <Box sx={{minHeight: "85vh", pt:"60px"}} component="main">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Hero/>
    </Box>
  )
}
